language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/
  - brew tap --repair
env:
  - PACKAGE=openssh
script:
  - brew audit travis/tap/$PACKAGE
  - brew install -v travis/tap/$PACKAGE
  - brew test travis/tap/$PACKAGE
